---
- name: Install sl with yum
  hosts: planetexpress
  gather_facts: yes

  tasks:

    - name: Install steam locomotive with yum
      yum:
        name: sl
        state: present
      become: yes # run as sudo
      when: ansible_distribution == "CentOS"

    - name: Install steam locomotive on Ubuntu machines
      apt:
        name: sl
        state: present
      become: yes # run as sudo
      when: ansible_distribution == "Ubuntu"

