---
- name: Exploring the template module and jinja expressions
  hosts: localhost
  gather_facts: no   # runs the "setup" module on remote hosts

  # these variables are used in the template ship.cfg.j2
  vars_files:
    - vars/planetexpress.yml

  tasks:
    - name: Configure spaceship registration
      template:  
        src: templates/ship.cfg.j2    # name of the template on ansible controller
        dest: ~/ship.cfg              # name of the completed file to be placed on the target system

